/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#pragma once

#include "mmagic_core_types.h"

struct mmagic_data;

struct mmagic_socket_config
{
    uint8_t reserved[0]; /* So that the struct is not empty */
};

struct mmagic_socket_data
{
    bool is_started;
    struct mmagic_socket_config config;
    /** Subsystem private data (to be allocated/managed by the subsystem implementation). */
    void *priv;
};

/**
 * Function to initialize the core data structure and register the ops functions.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_socket_init(struct mmagic_data *core);

/**
 * Function to start any of the core processes for the core socket subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_socket_start(struct mmagic_data *core);

/**
 * Function to check if the socket subsystem has been initialized.
 *
 * @param core   Reference to to global mmagic context struct.
 * @return       True if mmagic_core_socket_init has been called, false otherwise.
 */
bool mmagic_core_socket_is_started(struct mmagic_data *core);

/** Command arguments structure for socket_connect */
struct MM_PACKED mmagic_core_socket_connect_cmd_args
{
    struct string254 url;
    uint16_t port;
    enum mmagic_socket_proto protocol;
    bool enable_tls;
};

/** Response arguments structure for socket_connect */
struct MM_PACKED mmagic_core_socket_connect_rsp_args
{
    uint8_t stream_id;
};

enum mmagic_status mmagic_core_socket_connect(
    struct mmagic_data *core,
    const struct mmagic_core_socket_connect_cmd_args *cmd_args,
    struct mmagic_core_socket_connect_rsp_args *rsp_args);

/** Command arguments structure for socket_bind */
struct MM_PACKED mmagic_core_socket_bind_cmd_args
{
    uint16_t port;
    enum mmagic_socket_proto protocol;
};

/** Response arguments structure for socket_bind */
struct MM_PACKED mmagic_core_socket_bind_rsp_args
{
    uint8_t stream_id;
};

enum mmagic_status mmagic_core_socket_bind(struct mmagic_data *core,
                                           const struct mmagic_core_socket_bind_cmd_args *cmd_args,
                                           struct mmagic_core_socket_bind_rsp_args *rsp_args);

/** Command arguments structure for socket_recv */
struct MM_PACKED mmagic_core_socket_recv_cmd_args
{
    uint8_t stream_id;
    uint16_t len;
    uint32_t timeout;
};

/** Response arguments structure for socket_recv */
struct MM_PACKED mmagic_core_socket_recv_rsp_args
{
    struct raw1536 buffer;
};

enum mmagic_status mmagic_core_socket_recv(struct mmagic_data *core,
                                           const struct mmagic_core_socket_recv_cmd_args *cmd_args,
                                           struct mmagic_core_socket_recv_rsp_args *rsp_args);

/** Command arguments structure for socket_send */
struct MM_PACKED mmagic_core_socket_send_cmd_args
{
    uint8_t stream_id;
    struct raw1536 buffer;
};

enum mmagic_status mmagic_core_socket_send(struct mmagic_data *core,
                                           const struct mmagic_core_socket_send_cmd_args *cmd_args);

/** Command arguments structure for socket_read_poll */
struct MM_PACKED mmagic_core_socket_read_poll_cmd_args
{
    uint8_t stream_id;
    uint32_t timeout;
};

enum mmagic_status mmagic_core_socket_read_poll(
    struct mmagic_data *core,
    const struct mmagic_core_socket_read_poll_cmd_args *cmd_args);

/** Command arguments structure for socket_write_poll */
struct MM_PACKED mmagic_core_socket_write_poll_cmd_args
{
    uint8_t stream_id;
    uint32_t timeout;
};

enum mmagic_status mmagic_core_socket_write_poll(
    struct mmagic_data *core,
    const struct mmagic_core_socket_write_poll_cmd_args *cmd_args);

/** Command arguments structure for socket_accept */
struct MM_PACKED mmagic_core_socket_accept_cmd_args
{
    uint8_t stream_id;
};

/** Response arguments structure for socket_accept */
struct MM_PACKED mmagic_core_socket_accept_rsp_args
{
    uint8_t stream_id;
};

enum mmagic_status mmagic_core_socket_accept(
    struct mmagic_data *core,
    const struct mmagic_core_socket_accept_cmd_args *cmd_args,
    struct mmagic_core_socket_accept_rsp_args *rsp_args);

/** Command arguments structure for socket_close */
struct MM_PACKED mmagic_core_socket_close_cmd_args
{
    uint8_t stream_id;
};

enum mmagic_status mmagic_core_socket_close(
    struct mmagic_data *core,
    const struct mmagic_core_socket_close_cmd_args *cmd_args);

/** Command arguments structure for socket_set_rx_ready_evt_enabled */
struct MM_PACKED mmagic_core_socket_set_rx_ready_evt_enabled_cmd_args
{
    uint8_t stream_id;
    bool enabled;
};

enum mmagic_status mmagic_core_socket_set_rx_ready_evt_enabled(
    struct mmagic_data *core,
    const struct mmagic_core_socket_set_rx_ready_evt_enabled_cmd_args *cmd_args);

/*
 * ---------------------------------------------------------------------------------------------
 * Internal API: to be used by the implementation C file only.
 * ---------------------------------------------------------------------------------------------
 */

enum mmagic_status mmagic_core_event_socket_rx_ready(
    struct mmagic_data *core,
    const struct mmagic_core_event_socket_rx_ready_args *args);
