/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#include "mmconfig.h"
#include "mmagic_core_data.h"
#include "mmagic_core_mqtt.h"

/*
 * Maximum allowed length of any value string. Needs to accomodate WLAN password, IP and MAC address
 * strings.
 */
#define MAX_VAL_LEN 101

bool mmagic_core_mqtt_is_started(struct mmagic_data *core)
{
    return core->mqtt_data.is_started;
}

void mmagic_core_mqtt_load_all(struct mmagic_data *core)
{
    struct mmagic_mqtt_data *data = &core->mqtt_data;
    {
        char val[MAX_VAL_LEN] = { 0 };
        if (mmconfig_read_string("mqtt.keepalive_s", val, sizeof(val)) > 0)
        {
            (void)mmagic_string_to_uint16_t(&data->config.keepalive_s, val);
        }
    }
}

void mmagic_core_mqtt_save_all(struct mmagic_data *core)
{
    struct mmagic_mqtt_data *data = &core->mqtt_data;
    {
        char val[MAX_VAL_LEN];
        mmagic_uint16_t_to_string(data->config.keepalive_s, val, sizeof(val));
        mmconfig_write_string("mqtt.keepalive_s", val);
    }
}

enum mmagic_status mmagic_core_event_mqtt_message_received(
    struct mmagic_data *core,
    const struct mmagic_core_event_mqtt_message_received_args *args)
{
    const uint8_t *payload = (const uint8_t *)args;
    size_t payload_len = sizeof(*args);
    MMOSAL_ASSERT(core->event_fn != NULL);
    return core->event_fn(core->event_fn_arg,
                          mmagic_mqtt,
                          mmagic_mqtt_event_message_received,
                          payload,
                          payload_len);
}

enum mmagic_status mmagic_core_event_mqtt_broker_connection(
    struct mmagic_data *core,
    const struct mmagic_core_event_mqtt_broker_connection_args *args)
{
    const uint8_t *payload = (const uint8_t *)args;
    size_t payload_len = sizeof(*args);
    MMOSAL_ASSERT(core->event_fn != NULL);
    return core->event_fn(core->event_fn_arg,
                          mmagic_mqtt,
                          mmagic_mqtt_event_broker_connection,
                          payload,
                          payload_len);
}
