/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#pragma once

#include "mmagic_core_types.h"

struct mmagic_data;

struct mmagic_sys_config
{
    uint8_t reserved[0]; /* So that the struct is not empty */
};

struct mmagic_sys_data
{
    bool is_started;
    struct mmagic_sys_config config;
    /** Subsystem private data (to be allocated/managed by the subsystem implementation). */
    void *priv;
};

/**
 * Function to initialize the core data structure and register the ops functions.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_sys_init(struct mmagic_data *core);

/**
 * Function to start any of the core processes for the core sys subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_sys_start(struct mmagic_data *core);

/**
 * Function to check if the sys subsystem has been initialized.
 *
 * @param core   Reference to to global mmagic context struct.
 * @return       True if mmagic_core_sys_init has been called, false otherwise.
 */
bool mmagic_core_sys_is_started(struct mmagic_data *core);

enum mmagic_status mmagic_core_sys_reset(struct mmagic_data *core);

/** Command arguments structure for sys_deep_sleep */
struct MM_PACKED mmagic_core_sys_deep_sleep_cmd_args
{
    enum mmagic_deep_sleep_mode mode;
};

enum mmagic_status mmagic_core_sys_deep_sleep(
    struct mmagic_data *core,
    const struct mmagic_core_sys_deep_sleep_cmd_args *cmd_args);

/** Response arguments structure for sys_get_version */
struct MM_PACKED mmagic_core_sys_get_version_rsp_args
{
    struct struct_version_info results;
};

enum mmagic_status mmagic_core_sys_get_version(
    struct mmagic_data *core,
    struct mmagic_core_sys_get_version_rsp_args *rsp_args);

/** Command arguments structure for sys_get_stats */
struct MM_PACKED mmagic_core_sys_get_stats_cmd_args
{
    enum mmagic_subsystem_id subsystem;
    bool reset;
};

/** Response arguments structure for sys_get_stats */
struct MM_PACKED mmagic_core_sys_get_stats_rsp_args
{
    struct raw1600 buffer;
};

enum mmagic_status mmagic_core_sys_get_stats(
    struct mmagic_data *core,
    const struct mmagic_core_sys_get_stats_cmd_args *cmd_args,
    struct mmagic_core_sys_get_stats_rsp_args *rsp_args);
