/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#include "mmconfig.h"
#include "mmagic_core_data.h"
#include "mmagic_core_socket.h"

/*
 * Maximum allowed length of any value string. Needs to accomodate WLAN password, IP and MAC address
 * strings.
 */
#define MAX_VAL_LEN 101

bool mmagic_core_socket_is_started(struct mmagic_data *core)
{
    return core->socket_data.is_started;
}

enum mmagic_status mmagic_core_event_socket_rx_ready(
    struct mmagic_data *core,
    const struct mmagic_core_event_socket_rx_ready_args *args)
{
    const uint8_t *payload = (const uint8_t *)args;
    size_t payload_len = sizeof(*args);
    MMOSAL_ASSERT(core->event_fn != NULL);
    return core->event_fn(core->event_fn_arg,
                          mmagic_socket,
                          mmagic_socket_event_rx_ready,
                          payload,
                          payload_len);
}
