/*
 * Copyright 2026 Morse Micro
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Warning: this file is autogenerated. Do not modify by hand.
 */

#pragma once

#include "mmagic_core_types.h"

struct mmagic_data;

struct mmagic_ip_config
{
    /** IP address to use for a static network connection. This will take effect when
     * the reload command is successfully executed. */
    struct struct_ip_addr ip_addr;
    /** Netmask to use for a static network connection. This will take effect when the
     * reload command is successfully executed. */
    struct struct_ip_addr netmask;
    /** Gateway to use for a static network connection. This will take effect when the
     * reload command is successfully executed. */
    struct struct_ip_addr gateway;
    /** Primary DNS server IP address. If a value is specified this will override the
     * primary DNS server provided by DHCP (if any). Changes will take effect when the
     * reload command is successfully executed. */
    struct struct_ip_addr dns_server0;
    /** Secondary DNS server IP address. If a value is specified this will override the
     * secondary DNS server provided by DHCP (if any). Changes will take effect when
     * the reload command is successfully executed. Note that this option may be
     * ignored by some IP stacks. */
    struct struct_ip_addr dns_server1;
    /** True to enable DHCP for IP address configuration, or false to use the static
     * configuration given by ip_addr, netmask, and gateway. This will take effect when
     * the reload command is successfully executed. */
    bool dhcp_enabled;
    /** When set to true, IP link status notifications will be provided. Setting this to
     * false will suppress these notifications. Defaults to true. */
    bool link_status_evt_en;
};

struct mmagic_ip_data
{
    bool is_started;
    struct mmagic_ip_config config;
    /** Subsystem private data (to be allocated/managed by the subsystem implementation). */
    void *priv;
};

/**
 * Function to initialize the core data structure and register the ops functions.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_ip_init(struct mmagic_data *core);

/**
 * Function to load settings from persistent store for the core ip subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_ip_load_all(struct mmagic_data *core);

/**
 * Function to save settings to persistent store for the core ip subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_ip_save_all(struct mmagic_data *core);

/**
 * Function to start any of the core processes for the core ip subsystem.
 *
 * @param core   Reference to to global mmagic context struct.
 */
void mmagic_core_ip_start(struct mmagic_data *core);

/**
 * Function to check if the ip subsystem has been initialized.
 *
 * @param core   Reference to to global mmagic context struct.
 * @return       True if mmagic_core_ip_init has been called, false otherwise.
 */
bool mmagic_core_ip_is_started(struct mmagic_data *core);

/** Response arguments structure for ip_status */
struct MM_PACKED mmagic_core_ip_status_rsp_args
{
    struct struct_ip_status status;
};

enum mmagic_status mmagic_core_ip_status(struct mmagic_data *core,
                                         struct mmagic_core_ip_status_rsp_args *rsp_args);

enum mmagic_status mmagic_core_ip_reload(struct mmagic_data *core);

/*
 * ---------------------------------------------------------------------------------------------
 * Internal API: to be used by the implementation C file only.
 * ---------------------------------------------------------------------------------------------
 */

enum mmagic_status mmagic_core_event_ip_link_status(
    struct mmagic_data *core,
    const struct mmagic_core_event_ip_link_status_args *args);
